models:
  name: simple_cnn
  input_size: 28
  num_classes: 10

train:
  batch_size: 64
  epochs: 10
  learning_rate: 0.001
  seed: 42

data:
  dataset: FashionMNIST
  data_dir: ./data
  split_ratio: 0.8


