# configs/train.yaml
defaults:
  - model: simple_cnn
  - optimizer: sgd
  - criterion: cross_entropy
  - trainer: default
  - logging: base
  - _self_

seed: 42

data: 
  name: CIFAR10
  root: ${hydra:runtime.cwd}/datasets
  train: true
  batch_size: 64
  split_ratio: 0.8
  num_workers: 0

train: 
  epochs: 1
  device: cpu

